name: "${DOMAIN_NAME}"

services:
  mariadb:
    build:
      context: requirements/mariadb/
      tags: 
        - mariadb:mybuild
    image: mariadb:mybuild
    container_name: mariadb
    volumes:
      - db:/var/lib/mysql
    env_file: .env
    networks:
      - inception
    restart: always
    healthcheck:
      test: ["CMD", "/usr/local/bin/mariadb_healthcheck.sh"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    secrets:
      - db_root_password
      - db_password

  wordpress:
    build:
      context: requirements/wordpress/
      tags:
        - wordpress:mybuild
    image: wordpress:mybuild
    container_name: wordpress
    volumes:
      - wordpress:/var/www/wordpress
    env_file: .env
    networks:
      - inception
    restart: always 
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9000"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 3
    secrets:
        - db_password
        - wp_admin_password
        - wp_user_password

  nginx:
    build: 
      context: requirements/nginx/
      tags:
        - nginx:mybuild
    image: nginx:mybuild
    container_name: nginx
    ports:
      - "${APP_PORT}:443"
    volumes:
      - wordpress:/var/www/wordpress
    env_file: .env
    networks:
      - inception
    restart: always
    depends_on:
      wordpress:
        condition: service_healthy

secrets:
  db_root_password:
    file: ../secrets/db_root_password
  db_password:
    file: ../secrets/db_password
  wp_user_password:
    file: ../secrets/wp_user_password
  wp_admin_password:
    file: ../secrets/wp_admin_password

volumes:
  db:
    name: "${DOMAIN_NAME}_db"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${VOLUME_DIR}/db"
  wordpress:
    name: "${DOMAIN_NAME}_wordpress"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${VOLUME_DIR}/wordpress"

networks:
  inception:
    name: ${DOMAIN_NAME}_network
    driver: bridge
